Repository DevsKonnekt/DevsKonnekt, pull requests merged in 2024-02, with the labels that each got.

#116 Add coding challenges page and components
  Frontend/app/services/coding-challenges/page.jsx
  Frontend/components/services/coding-challenges/battle-types.jsx
  Frontend/components/services/coding-challenges/cta.jsx
  Frontend/components/services/coding-challenges/hero.jsx
  Frontend/components/services/coding-challenges/levels-and-achievements.jsx
  Frontend/components/services/coding-challenges/perkCard.jsx
  Frontend/components/services/coding-challenges/unleash.jsx
  Frontend/components/services/coding-challenges/whyUs.jsx
  Frontend/constants/index.js
  Frontend/public/images/services/coding-challenges/challenges.avif
  Frontend/public/images/services/coding-challenges/head-to-head-wars.avif
  Frontend/public/images/services/coding-challenges/hero.png
  Frontend/public/images/services/coding-challenges/job-offer.avif
  Frontend/public/images/services/coding-challenges/leaderboard.avif
  Frontend/public/images/services/coding-challenges/levels.svg
  Frontend/public/images/services/coding-challenges/solo-wars.svg
  Frontend/tailwind.config.js
Labels: enhancement

#117 Add JobsService page and components
  Frontend/app/services/jobs-service/page.jsx
  Frontend/components/NavBar.jsx
  Frontend/components/services/jobs-service/benefits.jsx
  Frontend/components/services/jobs-service/checkmate.jsx
  Frontend/components/services/jobs-service/cta.jsx
  Frontend/components/services/jobs-service/explore.jsx
  Frontend/components/services/jobs-service/hero.jsx
  Frontend/components/services/jobs-service/images.jsx
  Frontend/components/testimonials.jsx
  Frontend/public/images/services/jobs-service/checkmate.avif
  Frontend/public/images/services/jobs-service/connection-1.svg
  Frontend/public/images/services/jobs-service/connection-2.svg
  Frontend/public/images/services/jobs-service/connection-3.svg
  Frontend/public/images/services/jobs-service/hero.avif
Labels: enhancement

#133 Update user profiles creations
  .github/workflows/ethicalcheck.yml
  Backend/controllers/handleRefreshToken.js
  Backend/controllers/posts.js
  Backend/controllers/profile.js
  Backend/controllers/users.js
  Backend/index.js
  Backend/models/profiles.js
  Backend/models/tickets.js
  Backend/routes/posts.js
  Backend/routes/profile.js
  Frontend/app/api/webhooks/clerk/route.js
  Frontend/app/profile/[...id]/page.jsx
  Frontend/components/profile/about.jsx
  Frontend/components/profile/achievements.jsx
  Frontend/components/profile/aside.jsx
  Frontend/components/profile/details.jsx
  Frontend/components/profile/editProfile.jsx
  Frontend/components/profile/header.jsx
  Frontend/components/profile/project.jsx
  Frontend/components/ui/alert-dialog.jsx
  Frontend/components/ui/button.jsx
  Frontend/lib/actions/posts.actions.js
  Frontend/lib/actions/profile.actions.js
  Frontend/package-lock.json
  Frontend/package.json
Labels: enhancement

#139 Add upload functionality and create post feature
  Backend/models/posts.js
  Frontend/app/api/uploadthing/core.js
  Frontend/app/api/uploadthing/route.js
  Frontend/app/globals.css
  Frontend/app/layout.jsx
  Frontend/components/posts/createPost.jsx
  Frontend/components/posts/fileUploader.jsx
  Frontend/components/posts/postForm.jsx
  Frontend/components/profile/header.jsx
  Frontend/lib/actions/posts.actions.js
  Frontend/lib/uploadthing/uploadthing.js
  Frontend/lib/utils.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/images/icons/upload.png
  Frontend/tailwind.config.js
Labels: enhancement

#140 Refactor post and profile components, add loading state to modal and form components
  Backend/controllers/posts.js
  Backend/controllers/vote.js
  Backend/index.js
  Backend/models/votes.js
  Backend/routes/vote.js
  Frontend/components/myUI/modal.jsx
  Frontend/components/posts/createPost.jsx
  Frontend/components/posts/postForm.jsx
  Frontend/components/profile/about.jsx
  Frontend/components/profile/addSkills.jsx
  Frontend/components/profile/details.jsx
  Frontend/components/profile/header.jsx
  Frontend/components/profile/post.jsx
  Frontend/components/profile/postAvatar.jsx
  Frontend/components/profile/postsList.jsx
  Frontend/components/profile/skill.jsx
  Frontend/components/ui/tabs.jsx
  Frontend/next.config.js
Labels: enhancement

#145 Add new navigation links and refactor profile page components
  Backend/controllers/profile.js
  Backend/controllers/users.js
  Backend/models/users.js
  Frontend/app/about/page.jsx
  Frontend/app/chat/page.jsx
  Frontend/app/coding-challenges/page.jsx
  Frontend/app/contact/page.jsx
  Frontend/app/developers/page.jsx
  Frontend/app/events/page.jsx
  Frontend/app/loading.jsx
  Frontend/app/mentoship/page.jsx
  Frontend/app/not-found.jsx
  Frontend/app/profile/[...id]/page.jsx
  Frontend/components/NavBar.jsx
  Frontend/components/developers/leftSidebar.jsx
  Frontend/components/developers/rightSidebar.jsx
  Frontend/components/profile/about.jsx
  Frontend/components/profile/aside.jsx
  Frontend/components/profile/asideContent.jsx
  Frontend/components/profile/details.jsx
  Frontend/components/profile/header.jsx
  Frontend/components/profile/postsList.jsx
  Frontend/components/profile/profileCard.jsx
  Frontend/components/profile/profilesList.jsx
  Frontend/components/profile/projects/project.jsx
  Frontend/components/search.jsx
  Frontend/components/ui/input.jsx
  Frontend/components/ui/menubar.jsx
  Frontend/components/ui/navigation-menu.jsx
  Frontend/constants/index.js
  Frontend/constants/loading.json
  Frontend/constants/notFound.json
  Frontend/lib/actions/profile.actions.js
  Frontend/middleware.js
  Frontend/package-lock.json
  Frontend/package.json
Labels: enhancement

#147 Update NavBar component styling and refactor search component
  Frontend/app/forum/page.jsx
  Frontend/components/NavBar.jsx
  Frontend/components/forum/postsSort.jsx
  Frontend/components/shared/search.jsx
Labels: enhancement

#158 Remove venues routes and models
  Backend/controllers/events.js
  Backend/controllers/venues.js
  Backend/index.js
  Backend/models/amenities.js
  Backend/models/events.js
  Backend/models/venues.js
  Backend/routes/venues.js
Labels: model changes

#159 Add upvote and downvote functionality to posts
  Backend/controllers/posts.js
  Backend/index.js
  Backend/middlewares/authValidation.js
  Backend/middlewares/index.js
  Backend/middlewares/verifyJWT.js
  Backend/models/events.js
  Backend/models/posts.js
  Backend/models/votes.js
  Backend/routes/bookmarks.js
  Backend/routes/categories.js
  Backend/routes/comments.js
  Backend/routes/events.js
  Backend/routes/posts.js
  Backend/routes/productservice.js
  Backend/routes/profile.js
  Backend/routes/projects.js
  Backend/routes/reviews.js
  Backend/routes/skills.js
  Backend/routes/users.js
  Backend/routes/vote.js
  Frontend/app/layout.jsx
  Frontend/components/forum/forumPostsList.jsx
  Frontend/components/profile/post.jsx
  Frontend/components/ui/toast.jsx
  Frontend/lib/actions/posts.actions.js
Labels: enhancement, javascript

#163 Implement Event Creation Form & Integration
  Backend/.env.example
  Backend/controllers/categories.js
  Backend/controllers/events.js
  Frontend/.env.local.example
  Frontend/app/developers/page.jsx
  Frontend/app/events/page.jsx
  Frontend/app/forum/bookmarks/page.jsx
  Frontend/app/forum/page.jsx
  Frontend/app/posts/[...id]/page.jsx
  Frontend/app/posts/comments/[...id]/page.jsx
  Frontend/components/community/developers/leftSidebar.jsx
  Frontend/components/community/developers/rightSidebar.jsx
  Frontend/components/community/events/eventForm.jsx
  Frontend/components/community/forum/forumPostsList.jsx
  Frontend/components/community/forum/posts/comment.jsx
  Frontend/components/community/forum/posts/commentDetail.jsx
  Frontend/components/community/forum/posts/commentForm.jsx
  Frontend/components/community/forum/posts/commentsList.jsx
  Frontend/components/community/forum/posts/createPost.jsx
  Frontend/components/community/forum/posts/fileUploader.jsx
  Frontend/components/community/forum/posts/postDetail.jsx
  Frontend/components/community/forum/posts/postForm.jsx
  Frontend/components/community/forum/postsSort.jsx
  Frontend/components/myUI/responsiveDialog.jsx
  Frontend/components/profile/post.jsx
  Frontend/components/profile/postsList.jsx
  Frontend/components/profile/projects/projectForm.jsx
  Frontend/components/ui/calendar.jsx
  Frontend/components/ui/command.jsx
  Frontend/components/ui/dialog.jsx
  Frontend/components/ui/popover.jsx
  Frontend/lib/actions/categories.actions.js
  Frontend/lib/actions/events.actions.js
  Frontend/package-lock.json
  Frontend/package.json
  LICENSE
Labels: enhancement, javascript

#165 Refactor EventsPage component and add new features
  Backend/package-lock.json
  Frontend/app/error.jsx
  Frontend/app/events/[id]/page.jsx
  Frontend/app/events/page.jsx
  Frontend/app/forum/page.jsx
  Frontend/components/community/events/confirmEventDelete.jsx
  Frontend/components/community/events/eventCard.jsx
  Frontend/components/community/events/eventForm.jsx
  Frontend/components/community/events/eventsList.jsx
  Frontend/components/community/events/noEvents.jsx
  Frontend/components/community/forum/postsSort.jsx
  Frontend/constants/error.json
  Frontend/lib/actions/events.actions.js
Labels: enhancement, javascript

#170 Add ticket functionality
  Backend/controllers/events.js
  Backend/controllers/tickets.js
  Backend/index.js
  Backend/models/tickets.js
  Backend/routes/events.js
  Backend/routes/tickets.js
  Frontend/.env.local.example
  Frontend/app/api/webhooks/stripe/route.js
  Frontend/app/events/[id]/page.jsx
  Frontend/app/events/page.jsx
  Frontend/components/community/events/eventCard.jsx
  Frontend/components/community/events/eventDetail.jsx
  Frontend/components/community/events/eventsList.jsx
  Frontend/components/profile/about.jsx
  Frontend/components/profile/details.jsx
  Frontend/components/profile/header.jsx
  Frontend/components/profile/skill.jsx
  Frontend/components/shared/checkout.jsx
  Frontend/components/shared/checkoutButton.jsx
  Frontend/components/ui/badge.jsx
  Frontend/constants/error.json
  Frontend/lib/actions/events.actions.js
  Frontend/lib/actions/tickets.actions.js
  Frontend/lib/utils.js
  Frontend/package-lock.json
  Frontend/package.json
Labels: enhancement, javascript, frontend, backend
